version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/DigitalWallet.Api/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__RabbitMQ=amqp://admin:password123@rabbitmq:5672
